Add email field to personal info filter
samanthasgroup/django-webapps pull request #222
Opened 2023-08-14 23:53 UTC by dont-text-me

Tiny PR to enable filtering of the personal info list by email - to be used in the Tooljet dashboard

2023-08-15 18:19 UTC, Auch-Auch approved these changes

2023-08-15 18:19 UTC, Auch-Auch commented on tests/tests_api/test_personal_info.py
> +def test_personal_info_get_with_params_returns_200_and_data_with_existing_email(
The name is a little bit too big for my taste)

2023-08-15 23:36 UTC, lemontree210 commented
Thanks for the PR! Please extend the decorator so that `email` is shown in params in Swagger, like `registration_bot_chat_id` is.

2023-08-16 09:19 UTC, lemontree210 requested changes

2023-08-16 09:19 UTC, lemontree210 commented on api/views/personal_info.py
> +            OpenApiParameter(name="email", type=str, required=False),
```suggestion
```

Please revert this change, this is the wrong place for this parameter. It is a view for the bot that checks the existence of chat ID :)

2023-08-16 09:50 UTC, Auch-Auch commented
> In general, we decided that for dashboard we use routes with `/api/dashboard/` and dashboard serializers. So we cannot just add `email` field to the viewset that is serving the bot. Also, we should use a dashboard serializer, not bot serializer. I should have more time and brain power to do it a bit later, maybe @Auch-Auch you can help out as you remember our logic of dividing viewsets and serializers.

Do you mean that we need a dashboard viewset here? ah, yep, I overlooked that, we should do the same as `students/teachers/coordinators`, so split it up into internal and dashboard. I try will to do it today or tomorrow evening if nobody does it earlier.

2023-08-16 11:39 UTC, dont-text-me commented
ah, thanks for pointing that out! just managed to split things up, now looking like this: 
<img width="805" alt="image" src="https://github.com/samanthasgroup/django-webapps/assets/79531889/6426b50a-c652-4738-9645-68877e45f298">

Not sure if there is any point in splitting up the filters too, the email field will just sit unused by the bot

2023-08-17 23:16 UTC, lemontree210 reviewed
Hm, I wonder if creation of a separate serializer class (`DashboardStandalonePersonalInfoSerializer`) is really warranted. I need @Roxe322 's expert opinion on that :)

2023-08-18 09:37 UTC, Roxe322 approved these changes

2023-08-18 09:45 UTC, Roxe322 requested changes

2023-08-18 09:45 UTC, Roxe322 commented on api/serializers/personal_info.py
> +class DashboardStandalonePersonalInfoSerializer(serializers.ModelSerializer[PersonalInfo]):
Why "Standalone"? Maybe let's rename it to something like
`MinifiedDashboardPersonalInfoSerializer` as we have in other serializers?

2023-08-18 09:45 UTC, Roxe322 commented on tests/tests_api/test_personal_info.py
> +        path="/api/dashboard/personal_info/?email=unknownEmail@samanthasgroup.com",
```
api_client.get(
    "/api/dashboard/personal_info/",
    {"email": "unknownEmail@samanthasgroup.com"}
)
```

2023-08-18 09:45 UTC, Roxe322 commented on tests/tests_api/test_personal_info.py
> +        path="/api/dashboard/personal_info/?email=unknownEmail@samanthasgroup.com",
same above

2023-08-18 09:46 UTC, Roxe322 commented
Totally agree with adding "minified" serializer with only needed fields @lemontree210

2023-08-18 14:38 UTC, Roxe322 approved these changes

2023-08-18 21:07 UTC, dont-text-me commented
@lemontree210 i'll let you do the honours once youre happy with the pr👌

2023-08-19 09:21 UTC, lemontree210 commented
> @lemontree210 i'll let you do the honours once youre happy with the pr👌

Wait, what? 😆 

![image](https://github.com/samanthasgroup/django-webapps/assets/58207913/06747aed-ab46-40ed-ae4f-26d5fdee1de7)

2023-08-19 09:26 UTC, lemontree210 approved these changes
the honours are mine :)

2023-08-19 09:27 UTC, merged