feat(admin site): change `PersonalInfo.__str__()`, use it in other models
samanthasgroup/django-webapps pull request #366
Opened 2023-12-07 17:28 UTC by Ross1832

closes #361

2023-12-07 23:23 UTC, lemontree210 requested changes
I think that you should not have deleted `PersonalInfo.__str__()`.

Instead of creating the new property `.pk_full_name()` and then calling it, e.g. in `admin/group.py`, you could do:

```py
def __str__(self) -> str:
        return f"{self.pk}: {self.full_name}"
```
then, in group.py, you could just put

```py
format_html(
    ...
    ...,
    teacher
)
```
and that's it. As far as I understand `teacher.__str__()` will be called, which in turn will call `teacher.personal_info.__str__()`, which will return "123: John Smith".

Or am I missing something?
```

2023-12-07 23:28 UTC, lemontree210 requested changes

2023-12-07 23:28 UTC, lemontree210 commented on api/models/personal_info.py
> +        return f"{self.pk}: {self.full_name}"
```suggestion
    def __str__(self):
        return f"{self.personal_info}"
```

2023-12-12 14:53 UTC, Ross1832 commented
I have applied changes suggested in the feedback comments

2023-12-14 10:21 UTC, lemontree210 commented
> I have applied changes suggested in the feedback comments

Thank you! Perhaps I didn't explain well enough what I had in mind :)
I implemented this in #31ee964

2023-12-14 10:22 UTC, lemontree210 approved these changes
LGTM

2023-12-14 10:25 UTC, Roxe322 approved these changes

2023-12-14 10:26 UTC, merged